### ISSUE TITLE
Regular crashes in Crimson Skies 1.2.3

### ISSUE THREAD

**Issue by anpilley** [TheLimePixel/Crimson-Skies#35]
I clean installed Crimson Skies 1.2.3. I've had three crashes with identical stack traces while playing:

> java.lang.NullPointerException: Exception ticking world
>	at net.minecraft.item.Item.canApplyAtEnchantingTable(Item.java:1010)
>	at net.minecraft.enchantment.Enchantment.canApplyAtEnchantingTable(Enchantment.java:166)
>	at >ovh.corail.tombstone.enchantment.EnchantmentShadowStep.canApplyAtEnchantingTable(EnchantmentShadowStep.java:56)
>	at net.minecraft.enchantment.EnchantmentHelper.func_185291_a(EnchantmentHelper.java:416)
>	at net.minecraft.enchantment.EnchantmentHelper.func_77513_b(EnchantmentHelper.java:371)
>	at net.minecraft.enchantment.EnchantmentHelper.func_77504_a(EnchantmentHelper.java:333)
>	at net.minecraft.entity.EntityLiving.func_180483_b(EntityLiving.java:1148)
>	at net.minecraft.entity.monster.EntityZombie.func_180482_a(EntityZombie.java:486)
>	at betterwithaddons.entity.EntityKarateZombie.func_180482_a(EntityKarateZombie.java:216)
>	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:155)
>	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
>	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
>	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
>	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
>	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
>	at java.lang.Thread.run(Unknown Source)

Full crash report is here:
[crash-2018-04-20_17.11.04-server.txt](https://github.com/EmosewaPixel/Crimson-Skies/files/1933980/crash-2018-04-20_17.11.04-server.txt)

One of the crashes occurred while I was tabbed out of minecraft, so it doesn't appear to be triggered by anything specific I'm doing, and the other two occurred while I was just walking around.

**Comment by anpilley** [comment]
Looks like this is a fixed issue in Corail Tombstones: https://github.com/Corail31/tombstone_lite/issues/2

version 2.8.7 should address it, i'll test it out.
