### ISSUE TITLE
Crash with ore in kiln

### ISSUE THREAD

**Issue by yazug** [TheLimePixel/Crimson-Skies#53]
[15:27:57] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception while ticking a block
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:760) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.cout970.magneticraft.block.core.BlockBase.getPickBlock, parameter target
	at com.cout970.magneticraft.block.core.BlockBase.getPickBlock(BlockBase.kt) ~[BlockBase.class:?]
	at betterwithmods.module.gameplay.miniblocks.MiniBlockIngredient.apply(MiniBlockIngredient.java:51) ~[MiniBlockIngredient.class:?]
	at betterwithmods.common.registry.block.managers.CraftingManagerBlock.lambda$findRecipes$3(CraftingManagerBlock.java:55) ~[CraftingManagerBlock.class:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_66]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_66]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_66]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_66]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_66]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_66]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_66]
	at betterwithmods.common.registry.block.managers.CraftingManagerBlock.findRecipes(CraftingManagerBlock.java:55) ~[CraftingManagerBlock.class:?]
	at betterwithmods.common.registry.block.managers.CraftingManagerBlock.findRecipe(CraftingManagerBlock.java:59) ~[CraftingManagerBlock.class:?]
	at betterwithmods.common.registry.block.managers.KilnManagerBlock.canCraft(KilnManagerBlock.java:48) ~[KilnManagerBlock.class:?]
	at betterwithmods.common.blocks.BlockKiln.func_180650_b(BlockKiln.java:60) ~[BlockKiln.class:?]
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) ~[MinecraftServer.class:?]
	... 4 more
[15:27:57] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /home/jon/.MultiMC/instances/Crimson Skies-1.2.4.2/.minecraft/crash-reports/crash-2018-05-27_15.27.57-server.txt

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.cout970.magneticraft.block.core.BlockBase.getPickBlock(BlockBase.kt)
	at betterwithmods.module.gameplay.miniblocks.MiniBlockIngredient.apply(MiniBlockIngredient.java:51)
	at betterwithmods.common.registry.block.managers.CraftingManagerBlock.lambda$findRecipes$3(CraftingManagerBlock.java:55)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at betterwithmods.common.registry.block.managers.CraftingManagerBlock.findRecipes(CraftingManagerBlock.java:55)
	at betterwithmods.common.registry.block.managers.CraftingManagerBlock.findRecipe(CraftingManagerBlock.java:59)
	at betterwithmods.common.registry.block.managers.KilnManagerBlock.canCraft(KilnManagerBlock.java:48)
	at betterwithmods.common.blocks.BlockKiln.func_180650_b(BlockKiln.java:60)

-- Block being ticked --
Details:
	Block: betterwithmods:kiln[cook=0]
	Block location: World: (-1012,112,-999), Chunk: (at 12,7,9 in -64,-63; contains blocks -1024,0,-1008 to -1009,255,-993), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

[crash-2018-05-27_15.27.57-server.txt](https://github.com/EmosewaPixel/Crimson-Skies/files/2043429/crash-2018-05-27_15.27.57-server.txt)

**Comment by Bulut3** [comment]
well i have the same issue
